### ISSUE TITLE
CVE in lodash.template

### ISSUE THREAD

**Issue by mamacdon-surveymonkey** [oclif/plugin-help#218]
This package depends on `lodash.template`, which has a "high" severity CVE against it: https://app.snyk.io/vuln/SNYK-JS-LODASHTEMPLATE-1088054

`lodash.template` [is unmaintained](https://github.com/lodash/lodash/issues/5083#issuecomment-790184581) and will not receive security updates. `lodash` should be used instead.

**Comment by cfereday** [comment]
Thanks for raising this. Is there any movement with the PR opened to address this issue?
