### ISSUE TITLE
How is the --all option designed to be used?

### ISSUE THREAD

**Issue by Canuckaholic** [oclif/plugin-help#271]
I can't seem to figure out how to use the `--all` option such that when a user types in "help" from the root it shows all of the commands (root and topic commands), not just the root commands.

I've tried
```
czctl help --all
czctl --help --all
czctl -h --all
czctl --all
```

My solution right now is to provide my own Help class that extends this plugin, and do

```
constructor(config: Config.IConfig, opts?: Partial<HelpOptions>) {
        opts = { ...opts, all: true }
        super(config, opts)
}
```

Could an example be provided? Much appreciated.

**Comment by mdonnalley** [comment]
The correct use is `my-cli help my-topic --nested-commands` (the `--all` flag has been renamed to `--nested-commands`)
