### ISSUE TITLE
Package fails to install using `yarn` package manager

### ISSUE THREAD

**Issue by erezrokah** [oclif/plugin-help#349]
To reproduce, clone https://github.com/erezrokah/yarn-oclif-bug and run `yarn`.

Installation fails with out of memory error.

Workaround - add the following to `package.json`

```
"resolutions": {
    "@oclif/plugin-help": "3.2.17"
  }
```

This is probably a `yarn` issue, but was also triggered due to a change in this package.

**Comment by RodEsp** [comment]
Thanks for this issue and @erezrokah the report on https://github.com/oclif/plugin-help/pull/348#issuecomment-990929236 @erezrokah. This is currently our highest priority since it's affecting many CLI's downstream.

**Comment by erezrokah** [comment]
Thank you for the quick follow up @RodEsp ❤️

**Comment by cromwellryan** [comment]
We are tracking this at the `oclif` level here: oclif/oclif#758

**Comment by erezrokah** [comment]
Closing in favor of https://github.com/oclif/oclif/issues/758

**Comment by RodEsp** [comment]
There is a temporary fix out there for this now, please see https://github.com/oclif/oclif/issues/758#issue-1076987354 for more details.
