### ISSUE TITLE
Customized help output for command flags

### ISSUE THREAD

**Issue by childish-sambino** [oclif/plugin-help#37]
All of our commands inherit from a common base command that introduce two standard flags. It is possible for plugins to duplicate these flags (particularly, dynamically generated commands based on an Open API spec). Since they are global flags (and advanced usage patterns), we'd like to limit them to utilize single-character short form only and either hide the long form from help output or disallow it entirely. The other option is to use a more verbose name, but we don't like the UX of that either.

PR and some comments here: https://github.com/oclif/parser/pull/47

Feedback provided that this is not a good UX pattern on its own and a more powerful alternative is to support help overrides/templates that would allow for customizing flag help output.

This would support our needs.

**Comment by childish-sambino** [comment]
Considering adding a `helpName` (or `helpLabel`) flag option that takes the place of everything to the left of the `=`, similar to how [helpValue](https://github.com/oclif/plugin-help/blob/2dc953312f6a4102b173311fcc8c4a78029c1831/src/command.ts#L130) works for the right side of the `=`. This would allow for effectively hiding either the short or longer flag option from the help, but still support both.

**Comment by childish-sambino** [comment]
@jdxcode Is this something you're willing to support in _oclif_? It would help to unblock us.

**Comment by jdxcode** [comment]
@childish-sambino I'm stepping down from Heroku/oclif but @RasPhilCo should be able to assist

**Comment by RasPhilCo** [comment]
@childish-sambino I've merge above && created an issue for broader help templating

https://github.com/oclif/plugin-help/issues/39
