### ISSUE TITLE
Can I hide the "TOPICS" section in help?

### ISSUE THREAD

**Issue by boemekeld** [oclif/plugin-help#384]
Can I hide the "TOPICS" section in help?

I read all the documentation and tried to do this in several ways:

Editing "ocif.topics" in package.json.

Setting "hidden = true" in commands.

**Comment by dmatora** [comment]
Use
```
    "topics": {
      "plugins": {
        "hidden": true
      }
    }
```
To hide plugins topic.
List all topics to eliminate section entirely.

**Comment by mdonnalley** [comment]
If the above suggestion doesn't work for you, you can always implement [custom help](https://oclif.io/docs/help_classes#custom-help)
