### ISSUE TITLE
How to create custom help extending the Help class?

### ISSUE THREAD

**Issue by BravoNatalie** [oclif/plugin-help#431]
Using TS, how should I import the `Help` class from `'@oclif/plugin-help'`?

I already configure `oclif.helpClass` key to `package.json`:
```json
{
 "oclif": {
    "helpClass": "./dist/custom-help",
  }
}
```

And I've tried to import it in two different ways: 

<img width="675" alt="image" src="https://user-images.githubusercontent.com/37748828/202025345-c84d9121-ae85-4817-9e62-b4d48a261f8a.png">

<img width="767" alt="image" src="https://user-images.githubusercontent.com/37748828/202025406-7f30b094-c3ec-42b2-a44d-ab395260b7da.png">

**Comment by mdonnalley** [comment]
@BravoNatalie `Help` is exported from @oclif/core, not plugin-help: https://github.com/oclif/core/blob/1.20.4/src/help/index.ts#L45

Here's our custom help class if you want an example: https://github.com/salesforcecli/cli/blob/main/src/help/sfHelp.ts

Looks like the docs still mention plugin-help, I'll change those today to be more accurate
