### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by robcresswell** [oclif/plugin-help#50]
Sorry if I'm being stupid; the docs site (https://oclif.io) links to the github repo, which also contains no docs on what this does / how it works. Am I missing something?

**Comment by RasPhilCo** [comment]
@robcresswell can you elaborate, which link?

**Comment by robcresswell** [comment]
@RasPhilCo https://oclif.io/docs/plugins > has a reference to the help plugin, but neither the docs site, nor github, has much info on how it works?

**Comment by RasPhilCo** [comment]
Help ships with all CLI's atm. I'll update the docs. Help gives you `--help` and the `help` command.

**Comment by robcresswell** [comment]
Thanks! I've gathered roughly how it works and what it does; it would be useful to have it written down for others though
