### ISSUE TITLE
The new `npm-shrinkwrap.json` file contains unnecessary dependencies

### ISSUE THREAD

**Issue by benjamin-v-stax** [oclif/plugin-help#676]
**Describe the bug**
`npm install @oclif/plugin-help@^6.0.17` installs 1294 dependencies WHEREAS `@oclif/plugin-help@<=6.0.16` only installs 91 dependencies.
I have compared this repo's code between those two versions ([6.0.16...6.0.17](https://github.com/oclif/plugin-help/compare/6.0.16...6.0.17)) and the code is not importing nor depending on any additional dependencies.
The bug is that too many packages are being installed and the package do not appear to be needed.

**To Reproduce**
1. Create an empty node project using `npm init --yes` and install `@oclif/plugin-help`
1. ```npm install @oclif/plugin-help@^6.0.17```

**Expected behavior**
`@oclif/plugin-help` should only need 91 dependencies.
Perhaps the `npm-shrinkwrap.json` file needs to be cleaned up. Perhaps the `npm-shrinkwrap.json` file contains devDependencies that should not be in it?

**Environment (please complete the following information):**
- OS & version: `MacOS Sonoma 14.2.1`
- Shell/terminal: `zsh 5.9 (x86_64-apple-darwin23.0)`
- Node: `v20.11.1`

**Additional context**

**Comment by mdonnalley** [comment]
Take a look at this comment: https://github.com/oclif/plugin-warn-if-update-available/issues/553#issuecomment-1992294532
