### ISSUE TITLE
Takes command name on stdin, surprisingly

### ISSUE THREAD

**Issue by rrthomas** [oclif/plugin-help#735]
**Describe the bug**

The help plugin seems to optionally take a command name to give help about on stdin. This is surprising and undocumented.

**To Reproduce**

I generate a new cli with default settings:

```
oclif generate mynewcli
```

Then I run it and get an unexpected result:

```
$ echo foo | ./bin/dev.js help
Error: Command foo not found.
```

**Expected behavior**

I would expect stdin to be ignored.

**Screenshots**

n/a

**Environment (please complete the following information):**

- OS & version: Ubuntu 22.04.4 LTS
- Shell/terminal & version bash-5.1

**Additional context**

I came across this problem because my (trivial) test for `help` would always fail in my project's pre-push hook, which uses the `pre-push` package.

This turned out to be because in a git push hook, git supplies some information on stdin about the references being pushed, and this was being passed to my command. While this is arguably a bug in `pre-push` (and I have submitted a fix for it), it was surprising behaviour and took me a long time to track down.

I cannot see why oclif should behave like this, and I also can't see this behavior documented anywhere. Apologies if I have overlooked something, and thanks for oclif!

**Comment by mdonnalley** [comment]
@rrthomas 

The `help` command takes an optional argument, which you can see in the help output:


```
❯ bin/dev.js help
A new CLI generated with oclif

VERSION
  mycli/0.0.0 darwin-arm64 node-v20.13.1

USAGE
  $ mycli [COMMAND]

TOPICS
  hello    Say hello to the world and others
  plugins  List installed plugins.

COMMANDS
  hello
  help     Display help for mycli.
  plugins  List installed plugins.

```

The usage string follows the [docopts](http://docopt.org/) spec, which stipulates that optional arguments should be wrapped in square brackets.

You're right that this behavior isn't explicitly documented but it's standard behavior across most CLIs/unix commands. For example:

```
❯ echo mycli/src | ls
.eslintignore   .github     .mocharc.json     .vscode  dist          package-lock.json  README.md  test
.eslintrc.json  .gitignore  .prettierrc.json  bin      node_modules  package.json       src        tsconfig.json
```

**Comment by rrthomas** [comment]
I see that other oclif commands also  work like this, so it's not an issue specific to plugin-help. I'll refile.
